name: Node.js Package
on: [push]


jobs:
  backend:
    uses: ./.github/workflows/backend-tests.yml
    secrets: inherit
  frontend:
    uses: ./.github/workflows/frontend-tests.yml
    secrets: inherit
  release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    needs:
      - backend
      - frontend
    uses: ./.github/workflows/npmpublish.yml
    secrets: inherit
